// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoArtigos.Data;

namespace ProjetoArtigos.Migrations
{
    [DbContext(typeof(ProjetoDataContext))]
    [Migration("20201216162521_Migration_Inicial")]
    partial class Migration_Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ProjetoArtigos.Models.Cidades", b =>
                {
                    b.Property<int>("Id_Cidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Capital")
                        .HasColumnType("int");

                    b.Property<int>("Codigo_Ibge")
                        .HasColumnType("int");

                    b.Property<int>("Id_estado")
                        .HasColumnType("int");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("VARCHAR(2)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id_Cidade");

                    b.HasIndex("Id_estado");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("ProjetoArtigos.Models.Estados", b =>
                {
                    b.Property<int>("id_estado")
                        .HasColumnType("int");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("CHAR(2)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(40)");

                    b.HasKey("id_estado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("ProjetoArtigos.Models.Cidades", b =>
                {
                    b.HasOne("ProjetoArtigos.Models.Estados", "Estados")
                        .WithMany("Cidades")
                        .HasForeignKey("Id_estado")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Estados");
                });

            modelBuilder.Entity("ProjetoArtigos.Models.Estados", b =>
                {
                    b.Navigation("Cidades");
                });
#pragma warning restore 612, 618
        }
    }
}
